### PR TITLE
Add environment variable to disable Transaction extension in provided `pgstac` app

### PR DESCRIPTION
**Pull request by jtherrmann**
See https://github.com/stac-utils/stac-fastapi/issues/492

### CODE REVIEW

**Comment by geospatial-jeff** [comment]
@jtherrmann thinking of how to make this more applicable to the other extensions.  How about an environment variable `ENABLED_EXTENSIONS` which accepts a comma-delimited string (ex. `transactions,sort,query`) determining what extensions are added to the application.

If it is not present all extensions would be enabled.

**Comment by jtherrmann** [comment]
@geospatial-jeff Is there a use-case for disabling other extensions? The Transaction extension is the only one that I would want to disable, for security reasons, but I can't think of a reason for disabling any of the others.

**Comment by gadomski** [comment]
CI is breaking because we need to ceil the fastapi version (e.g. cb76e2e25e2fe7c285299bbc690133815432fd9f). @geospatial-jeff if you could approve #487, we can merge that to pick up the fix.

**Review by geospatial-jeff — APPROVED** [review]
This LGTM!  Thanks very much @jtherrmann 🙏

**Comment by jtherrmann** [comment]
Thanks @geospatial-jeff! When can we expect a release so that we can use this functionality (without installing from our fork)?

**Comment by geospatial-jeff** [comment]
I can cut the next release this weekend, there are a few other outstanding PRs I want to get merged.

**Comment by jtherrmann** [comment]
@geospatial-jeff Great, thanks!

**Comment by geospatial-jeff** [comment]
Sorry for the delay, I got a nasty case of the flu and have been out the past week.  I will cut a new release today @jtherrmann .  Thanks for your patience!

**Comment by jtherrmann** [comment]
@geospatial-jeff No worries, hope you're feeling better! Thanks!!

**Pull request merged**
