### PR TITLE
Properly type bbox and datetime

### PR DESCRIPTION
**Pull request by carderne**
**Related Issue(s):** 
This PR comment: https://github.com/stac-utils/stac-fastapi/pull/477#issuecomment-1280434016

**Description:**
WIP

**PR Checklist:**

- [x] Code is formatted and linted (run `pre-commit run --all-files`)
- [x] Tests pass (run `make test`)
- [x] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/stac-fastapi/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by jonhealy1** [comment]
Hi @carderne. This is pr is pretty old now.  Do you remember why it was never moved from Draft? It would be nice to add this work to the project as it looks really good. Thanks!

**Comment by carderne** [comment]
Hmm... I can't remember!

It was part of the work described in this comment https://github.com/stac-utils/stac-fastapi/pull/477#issuecomment-1280434016 (this PR is points 1+2 from that comment).

I'm not using stac-fastapi much right now but happy to get this PR over the line if you think useful!

**Comment by carderne** [comment]
This should be ready for review now...

**Comment by jonhealy1** [comment]
Hi @carderne thank you! I will review this when I get home in a few days.

**Review by jonhealy1 — APPROVED** [review]
Looks great! Thank you.

**Review by vincentsarago — APPROVED** [review]

**Pull request merged**
