### PR TITLE
update stac-version

### PR DESCRIPTION
**Pull request by vincentsarago**
ref #761

### CODE REVIEW

**Comment by vincentsarago** [comment]
@m-mohr I don't think there is any env variable that can change what is set in https://github.com/stac-utils/stac-fastapi/blob/main/stac_fastapi/api/stac_fastapi/api/app.py#L96 
https://github.com/stac-utils/stac-fastapi/blob/main/stac_fastapi/types/stac_fastapi/types/core.py#L287

Worth noting that I don't think this should be configurable because it all comes down to what version for the spec is supported by `stac-pydantic` 

I still think that it might be good to indicate which stac and stac-api version the application provide (from stac-pydantic)

**Comment by m-mohr** [comment]
Oh dang, I thought that's a env variable similar to STAC_API_TITLE etc. 
Seems like a misunderstanding then. In 1.0 and 1.1 the changes are not that big so I guess just updating the version number to 1.1.0 for some instances could make sense...

**Review by gadomski — APPROVED** [review]

**Comment by vincentsarago** [comment]
> So +1 to: "I still think that it might be good to indicate which stac and stac-api version the application provide (from stac-pydantic)" - could that be simply an env variable?

So there are 2 things:
- STAC VERSION: should indicate the STAC version specification returned by the endpoints, those should match what stac-pydantic has because we use it (optional) for validation, so I can't think about a situation where the STAC Version number would be different from the one from stac-pydantic 
- STAC API VERSION: this is almost the same (models used to validate response) but add also the spec for what endpoints are available. I'm having hard time to think why/how user would have a stac-fastapi based application which don't follow the version forwarded from stac-pydantic 

> could that be simply an env variable?

short answer: I don't think so

**Comment by jonhealy1** [comment]
A stac api should work with any stac version, even a catalog that may be a mix of v1 or v1.1?

**Comment by m-mohr** [comment]
Right, so we need stac-pydantic to support STAC v1.1.0 soon.

**Comment by vincentsarago** [comment]
@jonhealy1 

> A stac api should work with any stac version, even a catalog that may be a mix of v1 and v1.1?

🤷 depends if the 1.1 is backward compatible with 1.0

**Comment by m-mohr** [comment]
It is, I'd say... otherwise it should've been a 2.0.

**Comment by vincentsarago** [comment]
IMO: if someone wants to change the STAC VERSION, it means they have a custom version of stac-fastapi, which also means they don't really need to control this with an Env variable

**Pull request merged**
