### PR TITLE
prepare release 2.5.0

### PR DESCRIPTION
**Pull request by vincentsarago**

### CODE REVIEW

**Review by jonhealy1 — APPROVED** [review]
v2.5.0!!!

**Comment by gadomski** [comment]
> @gadomski 👋 any 👍 👎 

Hey sorry @vincentsarago , I'm ooo today (Monday), I can take a look tomorrow (Tuesday)

**Review by gadomski — APPROVED** [review]

**Comment by jonhealy1** [comment]
I'm assuming we just manually push a new release for the repo

**Comment by vincentsarago** [comment]
@jonhealy1 I've manually push a 2.5.0 tags 

it's now live on pypi https://pypi.org/project/stac-fastapi.api/2.5.0/ 🥳

**Comment by jonhealy1** [comment]
Looks great! How about here though? https://github.com/stac-utils/stac-fastapi/releases

**Pull request merged**
