### PR TITLE
Only use `add` method when the value is not ellipsis

### PR DESCRIPTION
**Pull request by nmandery**
**Related Issue(s):** #338

**Description:**

**PR Checklist:**

- [x] Code is formatted and linted (run `pre-commit run --all-files`)
- [x] Tests pass (run `make test`)
- [ ] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/master/CHANGES.md).

### CODE REVIEW

**Review by geospatial-jeff — APPROVED** [review]
Thanks for the PR @nmandery, nice catch!  Would you mind adding a test case to prevent regressions in the future?  I can help with this if you run into any problems.  Thanks 🙏

**Comment by nmandery** [comment]
I can create a testcase - sure. I see only testcases in the packages of the individual backends and not for the core, so I simply select one of the two backends - I would chose the sqlalchemy backend - and add the testcase there?

**Comment by geospatial-jeff** [comment]
Yes that would be great, thanks!

**Comment by nmandery** [comment]
Makes definitely sense to have this tested - I just added an testcase.

**Comment by geospatial-jeff** [comment]
@nmandery Please update the changelog and we can get this merged :)

**Comment by nmandery** [comment]
Alright - done :wink:

**Pull request merged**
