### PR TITLE
Allow intersects search to use GeometryCollection

### LINKED ISSUE #187: POST search with intersects containing GeometryCollection fails with 400
According to the STAC API spec, all GeoJSON shape types must be supported by intersects. GeometryCollection is explicity defined in the openapi spec as one of these. 

Running this search fails with a 400 error:

POST /search
```json
{"intersects": { "type": "GeometryCollection", "geometries": [{"type": "Point", "coordinates": [100.0, 0.0]}, {"type": "LineString", "coordinates": [[101.0, 0.0], [102.0, 1.0]]}]}}
```

### PR DESCRIPTION
**Pull request by jpolchlo**
**Related Issue(s):**
Closes #187 

**Description:**
An apparent oversight omitted GeometryCollection from the list of valid geometry types for intersection queries.  This PR remedies this.

**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [x] Tests pass (run `make test`)
- [x] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/stac-fastapi/blob/main/CHANGES.md).

### CODE REVIEW

**Review by gadomski — CHANGES_REQUESTED** [review]
Should include a unit test for both backends and a CHANGELOG entry.

**Review by gadomski — CHANGES_REQUESTED** [review]
This will need to be updated to have a no-backend test, if possible.

**Comment by jonhealy1** [comment]
Hi. @jpolchlo @gadomski Any thoughts on this pr and how we could test this now that the backends were removed? I'm not sure there's anything to really test here but it would be nice to have some.

@jpolchlo Do you have the time to remove the tests from this pr for now?

**Comment by gadomski** [comment]
> Any thoughts on this pr and how we could test this now that the backends were removed?

Not really — since it's just adding a type to a `Union` I guess no-test might be ok 🤷🏼 — each backend's tests could later be updated to prove that it _can_ accept a `GeometryCollection` (because they might not).

> @jpolchlo Do you have the time to remove the tests from this pr for now?

FYSA @jpolchlo isn't working the project that was using this repo anymore, so he may not have bandwidth to fix (in case he doesn't respond).

**Review by jonhealy1 — APPROVED** [review]
Looks great

**Pull request merged**
