### PR TITLE
Apply necessary environment variables for example docker-compose

### PR DESCRIPTION
**Pull request by moradology**
**Description:**
After the inclusion of pgstac 0.4.0, the example compose file was not working appropriately. Apparently, some environment variables now expected were not added (woops). This corrects that oversight

**PR Checklist:**

- [x] Code is formatted and linted (run `pre-commit run --all-files`)
- [x] Tests pass (run `make test`)
- [x] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by zstatmanweil** [comment]
Thanks for catching this, @moradology - could not figure out what was going on. It is working for me now too if that helps the reviewer!

**Comment by zstatmanweil** [comment]
Actually @moradology , I may have spoke too soon! The joplin data wasn't loaded for me when I ran `docker-compose build` and then `docker-compose app-pgstac` and I believe last time I ran it locally I didn't have to do anything special to get the data loaded. Perhaps I am misremembering though.  Did the joplin data load for you? I added the same environment variables to `loadjoplin-pgstac` in the docker-compose file but that didn't solve the issue.

**Comment by moradology** [comment]
Verifying right now, but it appears as though data loaded correctly for me. Might be a matter of blowing away container state first? I (this is overkill) like to `docker system prune -a` when in doubt

**Comment by zstatmanweil** [comment]
You are exactly right! It is working for me now. Sorry for the false alarm

**Comment by moradology** [comment]
No sweat. My propensity to set of false alarms is exactly why I blow away everything: you are *definitely* not alone

**Review by geospatial-jeff — APPROVED** [review]

**Pull request merged**
